from http.server import BaseHTTPRequestHandler,ThreadingHTTPServer
from urllib.parse import urlparse,parse_qs
import html,json
from meridian_ops import MeridianOps,RULES
O=MeridianOps()
CSS='''body{margin:0;background:#f1f0e9;color:#141512;font:14px Arial}header{height:68px;padding:0 32px;border-bottom:2px solid;display:flex;align-items:center;justify-content:space-between;background:#faf9f4}.brand{font-weight:900;letter-spacing:2px}a{color:#141512;text-decoration:none;font-weight:bold;margin-left:17px;font-size:11px;letter-spacing:1px}main{max-width:1400px;margin:auto;padding:32px}.ey{font-size:11px;letter-spacing:1.5px;color:#666}.metrics{display:grid;grid-template-columns:repeat(6,1fr);border:2px solid}.metric{min-height:120px;padding:16px;border-right:1px solid}.metric b{display:block;font-size:34px;margin-top:20px}h1{font-size:42px;letter-spacing:-2px;margin:10px 0 28px}h2{font-size:16px;letter-spacing:1px}.grid{display:grid;grid-template-columns:1.5fr 1fr;gap:20px}.panel{border:1px solid;padding:18px;background:#faf9f4;margin-top:20px}.dark{background:#141512;color:#faf9f4}button{background:#d7ff4f;border:1px solid;padding:11px 14px;font-weight:bold;cursor:pointer}input{padding:11px;border:1px solid;width:min(100%,440px)}table{width:100%;border-collapse:collapse}td,th{padding:10px 5px;border-bottom:1px solid #b9b9af;text-align:left}.ok{color:#287521}.review{color:#b33c2c}.trace{border-left:4px solid;padding:12px;margin:8px 0;background:#fff}.reject{border-left-color:#b33c2c}.selected{border-left-color:#367e2c}pre{white-space:pre-wrap;font:12px Consolas;background:#fff;padding:12px}@media(max-width:900px){.metrics{grid-template-columns:repeat(3,1fr)}.grid{grid-template-columns:1fr}nav{display:none}}'''
def e(x):return html.escape(str(x))
def page(t,b):return f'<!doctype html><meta charset="utf8"><title>{e(t)} · Meridian Ops</title><style>{CSS}</style><header><span class="brand">MERIDIAN OPS</span><nav><a href="/">OVERVIEW</a><a href="/breakdowns">BREAKDOWNS</a><a href="/context">CONTEXT</a><a href="/rules">RULES</a><a href="/audit">AUDIT</a><a href="/system">SYSTEM</a></nav></header><main>{b}</main>'
def overview():
 d=O.dashboard();cards=''.join(f'<div class=metric><span class=ey>{e(k.upper())}</span><b>{e(v)}</b></div>' for k,v in [('Breakdowns',d['breakdowns']),('Processed',d['processed']),('Needs review',d['needs_review']),('Quarantined',d['quarantined']),('Duplicates',d['duplicates']),('PII exposures',d['pii_exposures'])]);acts=''.join(f'<p>{e(x["ticket_id"])} · {e(x["status"])}</p>' for x in d['activity'])
 return f'<div class=ey>CONTEXT / RULE / DECISION / ACTION / EVIDENCE</div><h1>OPERATIONS CONTROL PLANE</h1><section class=metrics>{cards}</section><section class=grid><div class=panel><h2>Pipeline control</h2><p>Process a queue; persistent state prevents duplicate irreversible actions.</p><form method=post action=/run><button>RUN PIPELINE</button></form><p class=ey>{e(json.dumps(d["latest_run"] or {}))}</p></div><div class="panel dark"><h2>Live activity</h2>{acts}</div></section><section class=panel><h2>Ask Context</h2><form action=/context><input name=q placeholder="Why was vehicle CH81AQ4130 rejected?"><button>ASK</button></form></section>'
class H(BaseHTTPRequestHandler):
 def send(self,x,code=200,typ='text/html'):self.send_response(code);self.send_header('Content-Type',typ+'; charset=utf8');self.end_headers();self.wfile.write(x.encode())
 def do_GET(self):
  u=urlparse(self.path);q=parse_qs(u.query)
  if u.path=='/api/dashboard':return self.send(json.dumps(O.dashboard()),typ='application/json')
  if u.path=='/':return self.send(page('Overview',overview()))
  if u.path=='/breakdowns':
   rows=''.join(f'<tr><td><a href="/ticket?id={e(x["ticket_id"])}">{e(x["ticket_id"])}</a></td><td>{e(x["client"])}</td><td>{e(x["destination"])}</td><td class={"ok" if x["status"] in ("SENT","AWAITING_APPROVAL") else "review"}>{e(x["status"])}</td></tr>' for x in O.list_tickets());return self.send(page('Breakdowns',f'<div class=ey>BREAKDOWN QUEUE</div><h1>INCIDENTS</h1><section class=panel><table><tr><th>TICKET</th><th>CLIENT</th><th>DESTINATION</th><th>STATE</th></tr>{rows}</table></section>'))
  if u.path=='/ticket':
   r=O.get_ticket(q.get('id',[''])[0])
   if not r:return self.send(page('Incident','<h1>INSUFFICIENT DATA</h1>'),404)
   d=r['decision'];cs=''.join(f'<div class="trace {"reject" if x["status"]=="REJECTED" else "selected"}"><b>{e(x["vehicle"])} · {e(x["status"])}</b><br>{e("; ".join(x["reasons"]) or "Eligible under all evaluated hard constraints.")}</div>' for x in d['candidates']) or f'<div class=trace>{e(d["review"])}</div>';sel=d['selection'];decision=f'<div class="trace selected">SELECTED · {e(sel["vehicle"])}</div>' if sel else f'<div class="trace reject">{e(d["review"])}</div>';action=f'<form method=post action="/approve/{r["ticket_id"]}"><button>APPROVE & SEND COMMUNICATION</button></form>' if r['status']=='AWAITING_APPROVAL' else ''
   detail=''.join(f'<tr><td>{e(k)}</td><td>{e(v)}</td></tr>' for k,v in d['ticket'].items());return self.send(page('Incident',f'<div class=ey>INCIDENT / {e(r["ticket_id"])}</div><h1>{e(r["status"])}</h1><section class=grid><div class=panel><h2>Resolved context</h2><table>{detail}</table><p class=ey>{e(" | ".join(d["citations"]))}</p></div><div class="panel dark"><h2>Decision trace</h2>{decision}{action}</div></section><section class=panel><h2>Candidate vehicles</h2>{cs}</section>'))
  if u.path=='/context':
   query=q.get('q',[''])[0];a=O.context_answer(query) if query else None;result=f'<section class=panel><h2>Grounded answer</h2><p>{e(a["answer"])}</p><p class=ey>{e(" | ".join(a["citations"]))}</p><pre>{e(json.dumps({k:v for k,v in a.items() if k!="answer"},indent=2))}</pre></section>' if a else ''
   return self.send(page('Context',f'<div class=ey>GROUNDED CONTEXT EXPLORER</div><h1>ASK CONTEXT</h1><section class=panel><form><input name=q value="{e(query)}" placeholder="Vehicle, ticket, or R1"><button>ASK</button></form></section>{result}'))
  if u.path=='/rules':return self.send(page('Rules','<div class=ey>EXECUTABLE POLICY</div><h1>MERIDIAN RULES</h1><section class=panel><table><tr><th>RULE</th><th>CONDITION</th><th>EFFECT / SOURCE</th></tr>'+''.join(f'<tr><td>{e(x["rule_id"])}</td><td><b>{e(x["name"])}</b><br>{e(x["description"])}</td><td>{e(x["effect"])}<br><span class=ey>{e(x["source"])}</span></td></tr>' for x in RULES)+'</table></section>'))
  if u.path=='/audit':
   p=O.audit_dir/'audit.jsonl';return self.send(page('Audit','<div class=ey>SANITIZED, APPEND-ONLY</div><h1>AUDIT TRAIL</h1><section class=panel><pre>'+e('\n'.join(p.read_text().splitlines()[-100:]) if p.exists() else '')+'</pre></section>'))
  if u.path=='/system':
   d=O.dashboard();checks=[('PII PROTECTION',d['pii_exposures']==0),('SCHEMA ADAPTER',True),('ENTITY RESOLUTION',True),('PERSISTENT IDEMPOTENCY',True),('QUARANTINE',True),('APPROVAL GATE',True),('AUDIT TRAIL',True)];return self.send(page('System','<div class=ey>RELIABILITY STATUS</div><h1>SYSTEM INTEGRITY</h1><section class=panel><table>'+''.join(f'<tr><td>{e(k)}</td><td>{"✓ PASS" if v else "✕ REVIEW"}</td></tr>' for k,v in checks)+'</table><pre>'+e(json.dumps(d['latest_run'] or {},indent=2))+'</pre></section>'))
  self.send('Not Found',404)
 def do_POST(self):
  if self.path=='/run':O.run();self.send_response(303);self.send_header('Location','/');self.end_headers();return
  if self.path.startswith('/approve/'):O.approve(self.path.rsplit('/',1)[-1]);self.send_response(303);self.send_header('Location','/ticket?id='+self.path.rsplit('/',1)[-1]);self.end_headers();return
  self.send('Not Found',404)
if __name__=='__main__':print('Meridian Ops running at http://127.0.0.1:8000');ThreadingHTTPServer(('127.0.0.1',8000),H).serve_forever()
